/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package xyz.sathro.factory;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import xyz.sathro.factory.vulkan.Vulkan;

public class Engine {
	private static final Logger log = LogManager.getLogger(Engine.class);

	public static void main(String[] args) {
		log.info("START");
		if (args.length > 0) {
			Vulkan.debugMode = Boolean.parseBoolean(args[0]);
		}
		Vulkan.run();
		log.info("END");
	}
}
